### ISSUE TITLE
Raspberry Pi 3 Built in Wifi

### ISSUE THREAD

**Issue by ryanlaux** [ridiculousfish/one-second-dash#5]
Does this work with the built in wifi of the rpi 3?

**Comment by ridiculousfish** [comment]
Good question! The key question is whether the RPi3's builtin chipset supports monitor mode. [SO says no](http://raspberrypi.stackexchange.com/questions/43425/does-the-bcm43438-wifi-chip-in-raspberry-pi-3-support-monitor-mode) but it would be good to confirm.

**Comment by jamesb2147** [comment]
Consider it confirmed. I just got my RPi3 working today... by using a $3 dongle from eBay (searched for ridiculousfish's recommended RTL/Ralink chipset). Built in WiFi module doesn't seem to support necessary functions (probably promiscuous mode).

**Comment by ridiculousfish** [comment]
Bummer, but thanks for confirming jamesb. I appreciate it!
