### ISSUE TITLE
Multiple dash buttons

### ISSUE THREAD

**Issue by dan-r** [ridiculousfish/one-second-dash#7]
Hi,
Is there any built in way to perform different actions based on the MAC address of dash buttons?
Thanks,

**Comment by ridiculousfish** [comment]
I don't remember offhand if tcpdump outputs the MAC address. Let me know if you decide to find out!

**Comment by dan-r** [comment]
I'll have a look tomorrow and get back to you!

**Comment by dan-r** [comment]
Ended up just using different SSID's and checking SSID_TOKEN in the for loop, so never checked if tcpdump actually outputs the MAC

**Comment by ridiculousfish** [comment]
That works, thanks for closing the loop!
